version: "3.9"

services:
  localstack:
    image: localstack/localstack:2.3
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=dynamodb,cognito,events
      - DEFAULT_REGION=us-east-1
    volumes:
      - "./localstack:/var/lib/localstack"
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
    depends_on:
      - localstack
